version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    versioning-strategy: increase
    allow:
      - dependency-type: production
        update-type: all
      - dependency-type: direct
        update-type: all
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    target-branch: develop

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: ci
      include: scope
    target-branch: develop
